[package]
edition = "2021"
name = "moggie_runtime"
version = "0.1.0"
description = "Node module loading tools for applying custom transforms to imported modules at runtime"
repository = "https://github.com/moggie-framework/runtime.git"
license = "Apache-2.0"

authors = [
    "Louis Capitanchik <louis@weirdboi.com>"
]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
oxc = { version = "0.66", features = ["full"] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
